name: Deploy Workflow

on: push

jobs:
    Deploy:
       runs-on: ubuntu-latest
       steps:
          - name: Code Checkout
            uses: "actions/checkout@v3"
          - name: Build
            run: |
               npm ci
          - name: Lint
            run: |
               npm run lint
          - name: Test
            run: |
               npm test
          - name: Deploy
            run: echo "Deployed!!!"


