name: Issues Workflow

on:
  issues:
    types:
      - opened
      - labeled
      - closed

jobs:
    Issues:
       runs-on: ubuntu-latest
       steps:
          - name: Event Details
            run: |
               echo "${{ toJSON(github.event) }}"
               
       
